export const SET_QUESTION_LIST = 'SET_QUESTION_LIST';
export const SELECT_RANDOM_QUESTION = 'SELECT_RANDOM_QUESTION';
export const SUBMIT_QUIZ = 'SUBMIT_QUIZ';
export const RESTART_QUIZ = 'RESTART_QUIZ';
